<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{9858a2be-49fb-469e-93ec-63ca64f88c84}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[a;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>